# Metadata
title: Android Code
author: Maciej Nowak
email: kontakt@androidcode.pl
twitter: maciejnowa
github: android-code
baseurl: ""
url: "http://droidcode.it"
ghpage: "https://android-code.github.io"

# GTM
google-analytics: "UA-117930916-2"
google-analytics-enable: true

# Switches
lang: "en"
lang-switch-enable: true
post-share-enable: true
post-controls-enable: true
category-posts-show-less-number: 5
category-posts-show-less-enable: true
social-links-enable: true

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-paginate
  - jekyll-feed

# Pagination
paginate: 6
paginate_path: "blog/page:num/"

# Date
date_format: "%d %b %Y"

# Permalinks
permalink: /blog/:title/

# Include / Exclude
include: ['_pages']

# Compressing
compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]